name = "Blosc2"
uuid = "05405587-d2ae-42af-a06c-0e4c5bc87667"
authors = ["Alexandr Romanenko <waralex@gmail.com>"]
version = "0.1.0"

[deps]
Blosc2_jll = "d43303dc-dd0e-56c6-b0a8-331f4c8c9bfb"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"

[compat]
Blosc2_jll = "2.0.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
